require("user.options")
require("user.keymaps")
require("user.lazy")
require("user.colorscheme")
-- spec("plugins.themes.nordic")
-- spec("plugins.themes.moonfly")
-- spec("plugins.themes.nightfly")
-- spec("plugins.themes.rosePine")
-- spec("plugins.themes.catppuccin")
-- spec("plugins.themes.tokyonight")
